install:
  - "gem install bundler -v 1.9.5"
  - "bundle install --jobs=3 --retry=3"
  - "bundle exec rake neo4j:install[community-$NEO4J_VERSION]"
  - "bundle exec rake neo4j_spatial:install"
script:
  - "bundle exec rake neo4j:start default --trace"
  - "bundle exec rubocop"
language: ruby
jdk:
  - oraclejdk8
rvm:
  - 2.0.0
  - 2.2.4
  - 2.3.1
env:
  - NEO4J_VERSION=2.2.2 NEO4J_SPATIAL_VERSION=0.14
  - NEO4J_VERSION=2.3.3 NEO4J_SPATIAL_VERSION=0.15
  - NEO4J_VERSION=3.0.1 NEO4J_SPATIAL_VERSION=0.16
